version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
executors:
  node-executor:
    docker:
      - image: cimg/node:17.9.0
commands:
  verify-node-version:
    description: Check Node.js version used for the build
    steps:
      - run:
          name: 'Check Node.js version used for the build'
          command: 'node -v'
  setup:
    description: Set up the project to run commands against
    steps:
      - checkout
      - verify-node-version
      - run: npm install
jobs:
  lint_check:
    executor: node-executor
    steps:
      - setup
      - run: npm run lint
      - run: npm run prettier-check
  deploy-production:
    executor: node-executor
    steps:
      - setup
      - run: npm run build
      - aws-s3/sync:
          from: public
          to: 's3://yujinelson.com/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
workflows:
  version: 2
  validation:
    jobs:
      - lint_check
  deploy-production-workflow:
    jobs:
      - deploy-production:
          filters:
            branches:
              only: master
